### ISSUE TITLE
Unable to locate function ^FastPathGrantRelationLock$

### ISSUE THREAD

**Issue by FrankXMX** [jnidzwetzki/pg-lock-tracer#49]
root@LAPTOP-4OF1323N:/home/frank/github/pg-lock-tracer# pg_lock_tracer -x /home/frank/pgsql/bin/postgres -p 29661
===> Compiling BPF program
===> Attaching BPF probes
Traceback (most recent call last):
  File "/usr/local/bin/pg_lock_tracer", line 33, in <module>
    sys.exit(load_entry_point('pg-lock-tracer==0.5.4', 'console_scripts', 'pg_lock_tracer')())
  File "/usr/local/lib/python3.10/dist-packages/pg_lock_tracer/pg_lock_tracer.py", line 806, in main
    pg_lock_tracer.init()
  File "/usr/local/lib/python3.10/dist-packages/pg_lock_tracer/pg_lock_tracer.py", line 664, in init
    self.attach_probes()
  File "/usr/local/lib/python3.10/dist-packages/pg_lock_tracer/pg_lock_tracer.py", line 759, in attach_probes
    self.register_probe(
  File "/usr/local/lib/python3.10/dist-packages/pg_lock_tracer/pg_lock_tracer.py", line 708, in register_probe
    raise ValueError(f"Unable to locate function {function_regex}")
ValueError: Unable to locate function ^FastPathGrantRelationLock$

**Comment by yihong0618** [comment]
@FrankXMX sometimes with --debug info do not containers this I do not still figure out why.
you can just comment this FastPathGrantRelationLock instead of `FastPathGrantRelationLock ` can not track everything goes well.

**Comment by jnidzwetzki** [comment]
Hi @FrankXMX ,

Thanks for reaching out. I am interested in your PostgreSQL configuration. Might it be possible to share the output of `pg_config`?

**Comment by jnidzwetzki** [comment]
Hi @FrankXMX,

Is there anything I can do here at the moment? Or is this issue resolved and I can close it?
